### ISSUE TITLE
Melhorar validações na edição de questionários/perguntas

### ISSUE THREAD

**Issue by vitorhugonogueira** [missaopeixes/diagnosticosocial-server#17]
- Não permitir a remoção (desvincular) uma pergunta a um questionário, caso já sido respondida em entrevista naquele questionário.

- Não permitir a remoção (desvincular) uma opção de resposta de uma pergunta caso já tenha sido "escolhida"/"selecionada" em uma resposta de entrevista.

- Não permitir alteração do tipo de resposta de uma pergunta que já foi respondida. Obs: nesse caso apenas permitir alteração do nome da pergunta.

**Comment by ViniciusNogueiraS** [comment]
Resolução no _pull request_ #18.
