### ISSUE TITLE
Alterar sintaxe do Gulpfile para versão 4.0 

### ISSUE THREAD

**Issue by vitorhugonogueira** [missaopeixes/diagnosticosocial-server#3]
O sistema hoje não funciona com nodejs 12.x por uma incompatibilidade do nodejs 12 com gulp 3.

Por isso, visando possibilitar o uso do sistema com nodejs 12 (versão estável mais recente), deve-se ajustar o gulpfile e atualizar versão do gulp para a 4.0.

Após isso, testar o sistema com nodejs 12 e, em caso de sucesso, atualizar os requisitos no README.md.

**Comment by ViniciusNogueiraS** [comment]
Resolvido no pull request #5.
